//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Mx.Peppol.Xml.Sbdh
{

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [System.Xml.Serialization.XmlRootAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader",
        IsNullable = false)]
    public partial class CorrelationInformation
    {

        private System.DateTime requestingDocumentCreationDateTimeField;

        private bool requestingDocumentCreationDateTimeFieldSpecified;

        private string requestingDocumentInstanceIdentifierField;

        private System.DateTime expectedResponseDateTimeField;

        private bool expectedResponseDateTimeFieldSpecified;

        /// <remarks/>
        public System.DateTime RequestingDocumentCreationDateTime
        {
            get
            {
                return this.requestingDocumentCreationDateTimeField;
            }
            set
            {
                this.requestingDocumentCreationDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestingDocumentCreationDateTimeSpecified
        {
            get
            {
                return this.requestingDocumentCreationDateTimeFieldSpecified;
            }
            set
            {
                this.requestingDocumentCreationDateTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string RequestingDocumentInstanceIdentifier
        {
            get
            {
                return this.requestingDocumentInstanceIdentifierField;
            }
            set
            {
                this.requestingDocumentInstanceIdentifierField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ExpectedResponseDateTime
        {
            get
            {
                return this.expectedResponseDateTimeField;
            }
            set
            {
                this.expectedResponseDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpectedResponseDateTimeSpecified
        {
            get
            {
                return this.expectedResponseDateTimeFieldSpecified;
            }
            set
            {
                this.expectedResponseDateTimeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class Scope
    {

        private string typeField;

        private string instanceIdentifierField;

        private string identifierField;

        private object[] scopeInformationField;

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string InstanceIdentifier
        {
            get
            {
                return this.instanceIdentifierField;
            }
            set
            {
                this.instanceIdentifierField = value;
            }
        }

        /// <remarks/>
        public string Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ScopeInformation")]
        public object[] ScopeInformation
        {
            get
            {
                return this.scopeInformationField;
            }
            set
            {
                this.scopeInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class ManifestItem
    {

        private string mimeTypeQualifierCodeField;

        private string uniformResourceIdentifierField;

        private string descriptionField;

        private string languageCodeField;

        /// <remarks/>
        public string MimeTypeQualifierCode
        {
            get
            {
                return this.mimeTypeQualifierCodeField;
            }
            set
            {
                this.mimeTypeQualifierCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string UniformResourceIdentifier
        {
            get
            {
                return this.uniformResourceIdentifierField;
            }
            set
            {
                this.uniformResourceIdentifierField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string LanguageCode
        {
            get
            {
                return this.languageCodeField;
            }
            set
            {
                this.languageCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class Manifest
    {

        private string numberOfItemsField;

        private ManifestItem[] manifestItemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string NumberOfItems
        {
            get
            {
                return this.numberOfItemsField;
            }
            set
            {
                this.numberOfItemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ManifestItem")]
        public ManifestItem[] ManifestItem
        {
            get
            {
                return this.manifestItemField;
            }
            set
            {
                this.manifestItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class DocumentIdentification
    {

        private string standardField;

        private string typeVersionField;

        private string instanceIdentifierField;

        private string typeField;

        private bool multipleTypeField;

        private bool multipleTypeFieldSpecified;

        private System.DateTime creationDateAndTimeField;

        /// <remarks/>
        public string Standard
        {
            get
            {
                return this.standardField;
            }
            set
            {
                this.standardField = value;
            }
        }

        /// <remarks/>
        public string TypeVersion
        {
            get
            {
                return this.typeVersionField;
            }
            set
            {
                this.typeVersionField = value;
            }
        }

        /// <remarks/>
        public string InstanceIdentifier
        {
            get
            {
                return this.instanceIdentifierField;
            }
            set
            {
                this.instanceIdentifierField = value;
            }
        }

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public bool MultipleType
        {
            get
            {
                return this.multipleTypeField;
            }
            set
            {
                this.multipleTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MultipleTypeSpecified
        {
            get
            {
                return this.multipleTypeFieldSpecified;
            }
            set
            {
                this.multipleTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreationDateAndTime
        {
            get
            {
                return this.creationDateAndTimeField;
            }
            set
            {
                this.creationDateAndTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class ContactInformation
    {

        private string contactField;

        private string emailAddressField;

        private string faxNumberField;

        private string telephoneNumberField;

        private string contactTypeIdentifierField;

        /// <remarks/>
        public string Contact
        {
            get
            {
                return this.contactField;
            }
            set
            {
                this.contactField = value;
            }
        }

        /// <remarks/>
        public string EmailAddress
        {
            get
            {
                return this.emailAddressField;
            }
            set
            {
                this.emailAddressField = value;
            }
        }

        /// <remarks/>
        public string FaxNumber
        {
            get
            {
                return this.faxNumberField;
            }
            set
            {
                this.faxNumberField = value;
            }
        }

        /// <remarks/>
        public string TelephoneNumber
        {
            get
            {
                return this.telephoneNumberField;
            }
            set
            {
                this.telephoneNumberField = value;
            }
        }

        /// <remarks/>
        public string ContactTypeIdentifier
        {
            get
            {
                return this.contactTypeIdentifierField;
            }
            set
            {
                this.contactTypeIdentifierField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class PartnerIdentification
    {

        private string authorityField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Authority
        {
            get
            {
                return this.authorityField;
            }
            set
            {
                this.authorityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class Partner
    {

        private PartnerIdentification identifierField;

        private ContactInformation[] contactInformationField;

        /// <remarks/>
        public PartnerIdentification Identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContactInformation")]
        public ContactInformation[] ContactInformation
        {
            get
            {
                return this.contactInformationField;
            }
            set
            {
                this.contactInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class ServiceTransaction
    {

        private TypeOfServiceTransaction typeOfServiceTransactionField;

        private bool typeOfServiceTransactionFieldSpecified;

        private string isNonRepudiationRequiredField;

        private string isAuthenticationRequiredField;

        private string isNonRepudiationOfReceiptRequiredField;

        private string isIntelligibleCheckRequiredField;

        private string isApplicationErrorResponseRequestedField;

        private string timeToAcknowledgeReceiptField;

        private string timeToAcknowledgeAcceptanceField;

        private string timeToPerformField;

        private string recurrenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TypeOfServiceTransaction TypeOfServiceTransaction
        {
            get
            {
                return this.typeOfServiceTransactionField;
            }
            set
            {
                this.typeOfServiceTransactionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeOfServiceTransactionSpecified
        {
            get
            {
                return this.typeOfServiceTransactionFieldSpecified;
            }
            set
            {
                this.typeOfServiceTransactionFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsNonRepudiationRequired
        {
            get
            {
                return this.isNonRepudiationRequiredField;
            }
            set
            {
                this.isNonRepudiationRequiredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsAuthenticationRequired
        {
            get
            {
                return this.isAuthenticationRequiredField;
            }
            set
            {
                this.isAuthenticationRequiredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsNonRepudiationOfReceiptRequired
        {
            get
            {
                return this.isNonRepudiationOfReceiptRequiredField;
            }
            set
            {
                this.isNonRepudiationOfReceiptRequiredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsIntelligibleCheckRequired
        {
            get
            {
                return this.isIntelligibleCheckRequiredField;
            }
            set
            {
                this.isIntelligibleCheckRequiredField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsApplicationErrorResponseRequested
        {
            get
            {
                return this.isApplicationErrorResponseRequestedField;
            }
            set
            {
                this.isApplicationErrorResponseRequestedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeToAcknowledgeReceipt
        {
            get
            {
                return this.timeToAcknowledgeReceiptField;
            }
            set
            {
                this.timeToAcknowledgeReceiptField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeToAcknowledgeAcceptance
        {
            get
            {
                return this.timeToAcknowledgeAcceptanceField;
            }
            set
            {
                this.timeToAcknowledgeAcceptanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TimeToPerform
        {
            get
            {
                return this.timeToPerformField;
            }
            set
            {
                this.timeToPerformField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Recurrence
        {
            get
            {
                return this.recurrenceField;
            }
            set
            {
                this.recurrenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public enum TypeOfServiceTransaction
    {

        /// <remarks/>
        RequestingServiceTransaction,

        /// <remarks/>
        RespondingServiceTransaction,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [System.Xml.Serialization.XmlRootAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader",
        IsNullable = false)]
    public partial class BusinessService
    {

        private string businessServiceNameField;

        private ServiceTransaction serviceTransactionField;

        /// <remarks/>
        public string BusinessServiceName
        {
            get
            {
                return this.businessServiceNameField;
            }
            set
            {
                this.businessServiceNameField = value;
            }
        }

        /// <remarks/>
        public ServiceTransaction ServiceTransaction
        {
            get
            {
                return this.serviceTransactionField;
            }
            set
            {
                this.serviceTransactionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [System.Xml.Serialization.XmlRootAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader",
        IsNullable = false)]
    public partial class StandardBusinessDocumentHeader
    {

        private string headerVersionField;

        private Partner[] senderField;

        private Partner[] receiverField;

        private DocumentIdentification documentIdentificationField;

        private Manifest manifestField;

        private Scope[] businessScopeField;

        /// <remarks/>
        public string HeaderVersion
        {
            get
            {
                return this.headerVersionField;
            }
            set
            {
                this.headerVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sender")]
        public Partner[] Sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Receiver")]
        public Partner[] Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }

        /// <remarks/>
        public DocumentIdentification DocumentIdentification
        {
            get
            {
                return this.documentIdentificationField;
            }
            set
            {
                this.documentIdentificationField = value;
            }
        }

        /// <remarks/>
        public Manifest Manifest
        {
            get
            {
                return this.manifestField;
            }
            set
            {
                this.manifestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Scope[] BusinessScope
        {
            get
            {
                return this.businessScopeField;
            }
            set
            {
                this.businessScopeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [System.Xml.Serialization.XmlRootAttribute(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader",
        IsNullable = false)]
    public partial class StandardBusinessDocument
    {

        private StandardBusinessDocumentHeader standardBusinessDocumentHeaderField;

        private System.Xml.XmlElement anyField;

        /// <remarks/>
        public StandardBusinessDocumentHeader StandardBusinessDocumentHeader
        {
            get
            {
                return this.standardBusinessDocumentHeaderField;
            }
            set
            {
                this.standardBusinessDocumentHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
}