// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mx.Hyperway.Smp.Data;

namespace Mx.Hyperway.Smp.Migrations
{
    [DbContext(typeof(SmpContext))]
    partial class SmpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("Mx.Hyperway.Smp.Data.PeppolDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Identifier")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasAlternateKey("Identifier");

                    b.ToTable("PeppolDocuments");
                });

            modelBuilder.Entity("Mx.Hyperway.Smp.Data.PeppolParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Identifier")
                        .IsRequired();

                    b.Property<int>("SmpHostId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasAlternateKey("Identifier");

                    b.HasIndex("SmpHostId");

                    b.ToTable("PeppolParticipants");
                });

            modelBuilder.Entity("Mx.Hyperway.Smp.Data.PeppolProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Identifier")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasAlternateKey("Identifier");

                    b.ToTable("PeppolProcesses");
                });

            modelBuilder.Entity("Mx.Hyperway.Smp.Data.SmpHost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Hostname");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("SmpHosts");
                });

            modelBuilder.Entity("Mx.Hyperway.Smp.Data.SmpService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<int>("PeppolDocumentId");

                    b.Property<int>("PeppolParticipantId");

                    b.Property<int>("PeppolProcessId");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PeppolDocumentId");

                    b.HasIndex("PeppolParticipantId");

                    b.HasIndex("PeppolProcessId");

                    b.ToTable("SmpServices");
                });

            modelBuilder.Entity("Mx.Hyperway.Smp.Data.SmpServiceEndpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Certificate");

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Endpoint");

                    b.Property<string>("MinimumAuthenticationLevel");

                    b.Property<bool>("RequireBusinessLevelSignature");

                    b.Property<DateTime>("ServiceActivationDate");

                    b.Property<string>("ServiceDescription");

                    b.Property<DateTime>("ServiceExpirationDate");

                    b.Property<int>("SmpServiceId");

                    b.Property<string>("TechnicalContactUrl");

                    b.Property<string>("TransportProfile");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("SmpServiceId");

                    b.ToTable("SmpServiceEndpoints");
                });

            modelBuilder.Entity("Mx.Hyperway.Smp.Data.PeppolParticipant", b =>
                {
                    b.HasOne("Mx.Hyperway.Smp.Data.SmpHost", "SmpHost")
                        .WithMany()
                        .HasForeignKey("SmpHostId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mx.Hyperway.Smp.Data.SmpService", b =>
                {
                    b.HasOne("Mx.Hyperway.Smp.Data.PeppolDocument", "PeppolDocument")
                        .WithMany()
                        .HasForeignKey("PeppolDocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mx.Hyperway.Smp.Data.PeppolParticipant", "PeppolParticipant")
                        .WithMany()
                        .HasForeignKey("PeppolParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mx.Hyperway.Smp.Data.PeppolProcess", "PeppolProcess")
                        .WithMany()
                        .HasForeignKey("PeppolProcessId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mx.Hyperway.Smp.Data.SmpServiceEndpoint", b =>
                {
                    b.HasOne("Mx.Hyperway.Smp.Data.SmpService", "SmpService")
                        .WithMany("Endpoints")
                        .HasForeignKey("SmpServiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
